server:
  port: 8765

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: irm
    password: XingYouCai.COM1
    url: jdbc:mysql://192.168.150.232:3306/dbgirl?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.150.237
    port: 5672
    username: xiaoyan
    password: 123456
    
env: test-env
label: master
girl:
  name: xiaoyan哈哈
  age:  25
#   feign的超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
