spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: irm
    password: XingYouCai.COM1
    url: jdbc:mysql://192.168.150.232:3306/dbgirl?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.150.237
    port: 5672
    username: guest
    password: guest
